projeto/core/urls.py
from __future__ import unicode_literals
from django.conf.urls import url
from .views import HomeView, AboutView, HomeRedirectView

urlpatterns = [
   url(r'^$', HomeRedirectView.as_view(), name='home_redirect'),
   url(r'^home$', HomeView.as_view(), name='home'),
   url(r'^about$', AboutView.as_view(), name='about'),
]

projeto/projeto/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('core.urls')),
    url(r'usuario/', include('usuario.urls')),
    url(r'unidade/', include('unidade.urls')),
    url(r'triagem/', include('triagem.urls')),
    url(r'medicamento/', include('medicamento.urls')),
    url(r'consulta/', include('consulta.urls')),
    url(r'paciente/', include('paciente.urls')),
    url(r'fornecedor/', include('fornecedor.urls')),
   
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

projeto/core/models.py
from django.db import models

# Create your models here.

projeto/usuario/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, UserManager
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from datetime import timedelta, datetime

from utils.gerador_hash import gerar_hash


class AdministradorAtivoManager(UserManager):
    def get_queryset(self):
        return super().get_queryset().filter(tipo='ADMINISTRADOR', is_active=True)


class EnfermeiroAtivoManager(UserManager):
    def get_queryset(self):
        return super().get_queryset().filter(Q(tipo='ENFERMEIRO') | Q(tipo='ADMINISTRADOR'), is_active=True)
    
class TecnicoAtivoManager(UserManager):
    def get_queryset(self):
        return super().get_queryset().filter(tipo='TÉCNICO', is_active=True)

class MedicoAtivoManager(UserManager):
    def get_queryset(self):
        return super().get_queryset().filter(tipo='MÉDICO', is_active=True)        


class TecnicoEnfermeiroAtivoManager(UserManager):
   def get_queryset(self):
        return super().get_queryset().filter(Q(tipo='ENFERMEIRO') | Q(tipo='TÉCNICO'), is_active=True)

class Usuario(AbstractBaseUser):
    #1 campo da tupla fica no banco de dados
    #2 campo da tupla eh mostrado para o usuario
    TIPOS_USUARIOS = (
        ('ADMINISTRADOR', 'Administrador'),
        ('ENFERMEIRO', 'Enfermeiro' ),
        ('MÉDICO', 'Médico' ),
        ('TÉCNICO', 'Técnico' ),
    )

    USERNAME_FIELD = 'email'

    tipo = models.CharField('Tipo do usuário *', max_length=15, choices=TIPOS_USUARIOS, default='TÉCNICO', help_text='* Campos obrigatórios')
    nome = models.CharField('Nome completo *', max_length=100)
    email = models.EmailField('Email', unique=True, max_length=100, db_index=True)
    
    is_active = models.BooleanField('Ativo', default=False, help_text='Se ativo, o usuário tem permissão para acessar o sistema')
    slug = models.SlugField('Hash',max_length= 200,null=True,blank=True)

    objects = UserManager()
    administradores = AdministradorAtivoManager()
    enfermeiros = EnfermeiroAtivoManager()
    tecnicos = TecnicoAtivoManager()
    medicos = MedicoAtivoManager()
    tecnicos_enfermeiros = TecnicoEnfermeiroAtivoManager()

    class Meta:
        ordering            =   ['nome']
        verbose_name        =   ('usuário')
        verbose_name_plural =   ('usuários')

    def __str__(self):
        return '%s - %s' % (self.nome, self.email)


    def has_module_perms(self, app_label):
        return True

    def has_perm(self, perm, obj=None):
        return True

    def get_short_name(self):
        return self.nome[0:15].strip()

    def get_full_name(self):
        return self.nome

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = gerar_hash()
        self.nome = self.nome.upper()
        if not self.id:
            self.set_password(self.password) #criptografa a senha digitada no forms
        super(Usuario, self).save(*args, **kwargs)

    def get_id(self):
        return self.id

    @property
    def get_primeiro_nome(self):
        lista = self.nome.split(" ")
        return lista[0]

    @property
    def is_staff(self):
        if self.tipo == 'ADMINISTRADOR':
            return True
        return False

    @property
    def get_absolute_url(self):
        return reverse('usuario_update', args=[str(self.id)])

    @property
    def get_delete_url(self):
        return reverse('usuario_delete', args=[str(self.id)])

    @property
    def get_usuario_register_activate_url(self):
        return '%s%s' % (settings.DOMINIO_URL, reverse('usuario_register_activate', kwargs={'slug': self.slug}))

projeto/core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.base import TemplateView
from django.views.generic import RedirectView

from utils.decorators import LoginRequiredMixin, StaffRequiredMixin

class HomeRedirectView(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, **kwargs):
        return reverse('home')
        

class HomeView(LoginRequiredMixin, TemplateView):
	template_name = 'core/home.html'

class AboutView(TemplateView):
	template_name = 'core/about.html'

projeto/fornecedor/views.py
from __future__ import unicode_literals

from django.contrib import messages

from django.shortcuts import redirect

from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.urls import reverse

from utils.decorators import LoginRequiredMixin, StaffRequiredMixin, EnfermeiroRequiredMixin

from .models import Fornecedor


class FornecedorListView(LoginRequiredMixin, ListView):
    model = Fornecedor
 

class FornecedorCreateView(LoginRequiredMixin, EnfermeiroRequiredMixin, CreateView):
    model = Fornecedor
    fields = ['nome', 'cnpj', 'cidade', 'tipo_fornecedor','is_active']
    success_url = 'fornecedor_list'
    
    def get_success_url(self):
        messages.success(self.request, 'Fornecedor cadastrado com sucesso na plataforma!')
        return reverse(self.success_url)


class FornecedorUpdateView(LoginRequiredMixin, EnfermeiroRequiredMixin, UpdateView):
    model = Fornecedor
    fields = ['nome', 'cnpj', 'cidade', 'tipo_fornecedor','is_active']
    success_url = 'fornecedor_list'
    
    def get_success_url(self):
        messages.success(self.request, 'Fornecedor atualizado com sucesso na plataforma!')
        return reverse(self.success_url) 


class FornecedorDeleteView(LoginRequiredMixin, StaffRequiredMixin, DeleteView):
    model = Fornecedor
    success_url = 'fornecedor_list'

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL. If the object is protected, send an error message.
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        try:
            self.object.delete()
        except Exception as e:
            messages.error(request, 'Há dependências ligadas à esse Fornecedor, permissão negada!')
        return redirect(self.success_url)

projeto/core/templates/core/includes/_barra_status.html
{% load bootstrap3 %}
{% block navbar_bottom %}
<footer>
  <nav class="navbar navbar-default navbar-fixed-bottom">
    <div class="container">
      <div class="navbar-header">
        <br>
        <span class="label label-info">{% bootstrap_icon 'user' %}</span>
        <span class="label label-default">{{ user.get_short_name|upper }}</span>
        <span class="label label-info">{% bootstrap_icon 'credit-card' %}</span>
        <span class="label label-default">{{ user.get_tipo_display }}</span>
        <span class="label label-info">{% bootstrap_icon 'bookmark' %}</span>
        <span class="label label-default">Laboratório de Práticas da Computação UFN.</span>
      </div>
    </div>
  </nav>
</footer>
{% endblock %}

projeto/core/templates/core/includes/_menu_principal.html
{% load bootstrap3 %}

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">STC19</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class=""><a href="{% url 'home' %}"> {% bootstrap_icon 'home' %} Home <span class="sr-only">(current)</span></a></li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{% bootstrap_icon 'cog' %} Gestão básica <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'usuario_list' %}">{% bootstrap_icon 'user' %} Usuários</a></li>
            <li><a href="{% url 'unidade_list' %}">{% bootstrap_icon 'tower' %} Unidades de Atendimento</a></li>
            <li><a href="{% url 'medicamento_list' %}">{% bootstrap_icon 'plus-sign' %} Medicamentos </a></li>
            <li><a href="{% url 'fornecedor_list' %}">{% bootstrap_icon 'home' %} Fornecedores </a></li>
            
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{% bootstrap_icon 'user' %} Pacientes <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'paciente_list' %}">Todos</a></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{% bootstrap_icon 'list-alt' %} Triagens <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'triagem_list' %}">Todas</a></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{% bootstrap_icon 'plus' %} Consultas <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'consulta_list' %}">Todas</a></li>
          </ul>
        </li>

        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{% bootstrap_icon 'print' %} Relatórios <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Filtros gerais</a></li>
            <li><a href="#">Por edital</a></li>
            <li><a href="#">Anomalias</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Impressões</a></li>
          </ul>
        </li> -->
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'about' %}">{% bootstrap_icon 'question-sign' %} Sobre</a></li>
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Login <span class="caret"></span></a>
          <ul class="dropdown-menu">
            
            <li><a href="{% url 'logout' %}?next=/">Sair</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>